spring:
  datasource:
    url: datasource_url
    username: datasource_username
    password: datasource_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    team24: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled:
      show-details: always
  health:
    db:
      enabled: true
