# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
<<<<<<< HEAD
<<<<<<< HEAD
    branches: [ "be-deploy" ]
  pull_request:
    branches: [ "be-deploy" ]
=======
    branches: [ "team-24" ]
  pull_request:
    branches: [ "team-24" ]
>>>>>>> 250e9cf (chore: (BE)github actions.yml init)
=======
    branches: [ "be-deploy" ]
  pull_request:
    branches: [ "be-deploy" ]
>>>>>>> 12fb95e (fix: gradle.yml 브랜치 수정)

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
